/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_book_free: (a: number, b: number) => void;
export const book_apply: (a: number, b: number, c: number) => [number, number];
export const book_apply_remote: (a: number, b: number, c: number) => [number, number];
export const book_can_redo: (a: number) => number;
export const book_can_undo: (a: number) => number;
export const book_cell: (a: number, b: number, c: number, d: number) => [number, number];
export const book_cells: (a: number, b: number) => [number, number];
export const book_charts: (a: number) => [number, number];
export const book_check_validation: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const book_checks: (a: number) => [number, number];
export const book_eval_at: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const book_format_number: (a: number, b: number, c: number) => [number, number];
export const book_from_json: (a: number, b: number) => [number, number, number];
export const book_list_entries: (a: number, b: number, c: number, d: number) => [number, number];
export const book_name: (a: number) => [number, number];
export const book_names: (a: number) => [number, number];
export const book_new: (a: number, b: number) => number;
export const book_preview: (a: number, b: number, c: number, d: number) => [number, number];
export const book_range_hash: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const book_range_values: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const book_redo: (a: number) => [number, number];
export const book_resolve_values: (a: number, b: number, c: number, d: number) => [number, number];
export const book_set_name: (a: number, b: number, c: number) => void;
export const book_set_now: (a: number, b: number) => void;
export const book_shift_formula: (a: number, b: number, c: number, d: number) => [number, number];
export const book_shift_formula_row: (a: number, b: number, c: number, d: number) => [number, number];
export const book_signoff_status: (a: number, b: number) => [number, number];
export const book_table_id: (a: number, b: number, c: number) => number;
export const book_tables: (a: number) => [number, number];
export const book_to_json: (a: number) => [number, number];
export const book_trace: (a: number, b: number, c: number, d: number) => [number, number];
export const book_undo: (a: number) => [number, number];
export const book_version: () => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
